# Puerto
server.port=8080

# Base de datos H2
spring.datasource.url=jdbc:h2:mem:climalertdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mail
spring.mail.host=${SPRING_MAIL_HOST:localhost}
spring.mail.port=${SPRING_MAIL_PORT:1025}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
# Ya no requerimos autenticación SSL para probar en local
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# Climalert Custom Properties
# Limites para generar alerta
climalert.alert.max-temperature=35
climalert.alert.min-humidity=60

# Emails destinatarios
climalert.notification.recipients=${NOTIFICATION_RECIPIENTS:admin@clima.com}
climalert.notification.enabled=true

# Weather API
weather.api.url=http://api.weatherapi.com/v1/current.json
weather.api.key=${WEATHER_API_KEY:fictional-key-1234}
weather.api.location=${CLIMALERT_LOCATION:CABA}
